# Numpy and Array Basics

# Import NumPY Library

In [1]:
import numpy as np

# Creating a NumPy Array

## Basic ndarray

In [2]:
a = [10,20,30,40]

In [3]:
type(a)

list

In [4]:
x = np.array(a)

In [5]:
print(x)

[10 20 30 40]


In [6]:
type(x)

numpy.ndarray

In [7]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])

In [8]:
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [9]:
a = [1,2,3,4]
b = [10,20,30]
x = np.array([a,b])

C:\Users\repan\AppData\Local\Temp\ipykernel_20408\1620225346.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([a,b])


In [10]:
print(x)

[list([1, 2, 3, 4]) list([10, 20, 30])]


In [11]:
x = np.array([1,2,3,4], dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [12]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


## Array of zeros

In [13]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Array of ones

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1])

## Random numbers in ndarrays

In [16]:
x = np.random.rand(2,5)

In [17]:
print(x)

[[0.68404332 0.28598013 0.51076013 0.9751243  0.7095091 ]
 [0.28831428 0.35731131 0.38045858 0.78441924 0.23315269]]


In [18]:
np.random.rand??

In [19]:
np.random.randint(1,20, size = (3,3))

array([[ 8, 18,  1],
       [12, 10, 13],
       [19,  4,  6]])

In [20]:
np.random.randint??

In [21]:
np.random.randn(2,5)

array([[-1.20191542,  0.74899155, -0.86812756, -0.39905165,  0.73439043],
       [-0.96096274, -0.26016993, -0.64825341, -0.24942407, -0.49587732]])

In [22]:
np.random.randn??

In [23]:
np.random.choice([2,3,4,7,8,10])

10

## An array of your choice

In [24]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [25]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

## Identity matrix

In [26]:
x = np.eye(4, k = -1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [26]:
np.eye??

## Evenly spaced ndarray

In [27]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [29]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# $\frac{end-start}{n-1}$

# Shape and Reshaping of NumPy Array

## Dimension of nparray

In [31]:
a = [10,20,30,40,50]
x = np.array(a)
print(x)

[10 20 30 40 50]


In [32]:
x.ndim

1

In [33]:
b = [1,2,3,4,5]
y = np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [34]:
y.ndim

2

## Shape of NumPy array

In [35]:
y.shape

(2, 5)

In [36]:
y.size

10

## Reshaping a NumPy array

In [37]:
a = np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [38]:
np.reshape(a, (2,2))

array([[ 3,  6],
       [ 9, 12]])

In [39]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [40]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
x.size

15

In [42]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

## Transpose of a NumPy array

In [43]:
x = np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [44]:
y = x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [45]:
z = np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [46]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

# Indexing and Slicing of NumPy Array

## 1D NumPy arrays

In [47]:
a = np.arange(1,10)

In [48]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [49]:
a[2:6]

array([3, 4, 5, 6])

# 2-D NumPy arrays

In [50]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
x[1,2]

6

In [52]:
x[1][2]

6

In [53]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

# Stacking and Concatenating NumPy Arrays

## Stacking

In [54]:
a = np.arange(1,6)
b = np.arange(6,11)

In [55]:
print(a)

[1 2 3 4 5]


In [58]:
print(b)

[ 6  7  8  9 10]


In [59]:
x = np.vstack((a,b))

In [60]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [61]:
x = np.hstack((a,b))

In [62]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


## Concatenating

In [63]:
a = np.arange(1,10).reshape(3,3)

In [64]:
b = np.arange(10,19).reshape(3,3)

In [65]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [67]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [68]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

# Broadcasting in NumPy arrays

In [69]:
a = np.arange(10,21,2)

In [70]:
b = np.array([[2],[2]])

In [71]:
print(a)

[10 12 14 16 18 20]


In [72]:
print(b)

[[2]
 [2]]


In [73]:
z = a+b
print(z)

[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [74]:
a = np.arange(10,21,2)

In [75]:
a+2

array([12, 14, 16, 18, 20, 22])

In [76]:
a - b

array([[ 8, 10, 12, 14, 16, 18],
       [ 8, 10, 12, 14, 16, 18]])

In [77]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [78]:
a = np.ones((3,3))
b = np.array([2])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [79]:
print(b)

[2]


In [80]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [81]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

# Arithmetic Operations on NumPy Array

In [82]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [83]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [84]:
a - 1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [85]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [86]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [87]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [88]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [89]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Aggregate Function

## Mean, Median and Standard deviation

In [90]:
a = np.arange(5,15,2)

In [91]:
print(a)

[ 5  7  9 11 13]


In [92]:
np.mean(a)

9.0

In [93]:
np.median(a)

9.0

In [94]:
np.std(a)

2.8284271247461903

## Min-Max values

In [95]:
a = np.array([[1,6],[4,3]])
print(a)

[[1 6]
 [4 3]]


In [96]:
print(np.min(a, axis = 0))

[1 3]


In [97]:
print(np.min(a, axis = 1))

[1 3]


In [98]:
print(np.max(a, axis = 1))

[6 4]


In [99]:
print(np.max(a, axis = 0))

[4 6]


# Sorting

In [100]:
a = np.array([1,4,3,10,20])

In [101]:
x = np.sort(a, kind = 'mergesort')

In [102]:
print(x)

[ 1  3  4 10 20]


# Matrix Multiplication

In [103]:
A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3))

In [104]:
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [105]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [106]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [107]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])